### ISSUE TITLE
hi~gurkirt. will u upload the inference script in the few weeks?

### ISSUE THREAD

**Issue by O-Givenchy** [gurkirt/FPN.pytorch1.0#3]
recently i have trained a model based RESNET101 and achieved 81.2mAP.
now i have some imgs and i wanna test the model's performance (draw the bbox on the imgs) and whether u will upload the inference script in the future?  :)

**Comment by gurkirt** [comment]
It is already there as evaluate.py

**Comment by O-Givenchy** [comment]
> It is already there as evaluate.py

i tried that , but the evaluate.py only  calculate the  value of mAP and write the results into a .txt file.
i guess end-to-end img testing demo is not implemented ( the input of demo should be some imgs and outputs are imgs predicted by model and these imgs should be drawn with labels , bouding boxs and probabilities)...

btw .. have u tested the three kinds of loss function~ . i  just wonder which is the best....
AND I FOUND SOMETHING WRONG IN LINE 244 OF train.py. I GUESS U WANT TO WRITE FOCAL LOSS INSTEAD OF YOLO :)

**Comment by gurkirt** [comment]
there is an extract_feature.py which take images as input. 

Loss function part is under development!

**Comment by O-Givenchy** [comment]
> there is an extract_feature.py which take images as input.
> 
> Loss function part is under development!

yea i found it ~ but the extract_feature.py is based COCO dataset and  i confused that whether the code also supports VOC datasets or not ?   if it cannot support .what parts should I modify to support VOC.~

i choose five imgs from voc 2007 test and put them into a folder named rgb-images. but i got the outcome like this:
```
downloaded: <list_reverseiterator object at 0x7f1ad5bb9a58>
Traceback (most recent call last):
  File "extract_features.py", line 283, in <module>
    images = os.listdir(viddir)
NotADirectoryError: [Errno 20] Not a directory: '/home/cyrus/code/fpn/ohem-fpn/prep/demo/rgb-images/000046.jpg/'

```

**Comment by gurkirt** [comment]
I have uploaded demo.py.

You can check that out.

**Comment by O-Givenchy** [comment]
> I have uploaded demo.py.
> 
> You can check that out.

thx for ur upload.  its very very useful for me to visualize the model's performance ~ :+1: :+1:

**Comment by gurkirt** [comment]
@O-Givenchy You can check out the latest version https://github.com/gurkirt/RetinaNet.pytorch.1.x
performs better. OHEM is same as Focal loss!
