### ISSUE TITLE
inference time too looooong :(

### ISSUE THREAD

**Issue by O-Givenchy** [gurkirt/FPN.pytorch1.0#4]
hi gurkirt.
recently i trained this model on coco dataset .
its weird that when i run evaluate.py on coco the detect time was too long .
```
Forward Time 0.626
im_detect: 4/4952 time taken 12.002
NMS stuff Time 10.017
Forward Time 0.102
im_detect: 84/4952 time taken 176.985
NMS stuff Time 9.978
Forward Time 0.103
im_detect: 164/4952 time taken 169.440
NMS stuff Time 9.542
Forward Time 0.098
im_detect: 244/4952 time taken 193.901
```

btw its very normal when i evaluate the voc dataset.
```
Forward Time 0.133
im_detect: 4/4952 time taken 2.477
NMS stuff Time 1.104
Forward Time 0.082
im_detect: 84/4952 time taken 15.756
NMS stuff Time 0.658
Forward Time 0.083
im_detect: 164/4952 time taken 16.580
NMS stuff Time 0.708
Forward Time 0.083
im_detect: 244/4952 time taken 14.848
NMS stuff Time 0.505
Forward Time 0.087
im_detect: 324/4952 time taken 16.605
NMS stuff Time 0.736
Forward Time 0.084
im_detect: 404/4952 time taken 14.983
NMS stuff Time 0.723
Forward Time 0.083
im_detect: 484/4952 time taken 16.381
NMS stuff Time 0.666
Forward Time 0.085
im_detect: 564/4952 time taken 16.034
NMS stuff Time 0.777
```
could u do me a favor to solve it ?

**Comment by gurkirt** [comment]
Most of the time is taken by classwise nms. During evaluation forward pass time is negligible. Coco has more classes hence more time on nms this. You can see that from the above log.

**Comment by O-Givenchy** [comment]
i have two questions about coco DATASET . 

**1st :**
i noticed that u used train2017 and val2017 for training and evaluation respectively.

i wanna know what should i do if i want to use test2017 for evaluation rather than val2017.

btw i didnt find the annotation files of test2017 (maybe named instances_test2017.json ... i dont know :)

**2st :**
is the calculation of coco mAP value based on AP at IoU=0.50:0.05:0.95 in this work?

and how can i calculate the AP value for small medium and large objects?

**Comment by gurkirt** [comment]
1. You can use evaluate.py to dump detection for test2017 and then upload on coco server, test2017.json is not publically available.
2. It is there in evaluate.py, please the README.md

You can increase conf_thresh to 0.05 to speed up the evaluation.
