### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by AdamLTy** [gurkirt/FPN.pytorch1.0#9]
hi
where should i download the pretrained model

**Comment by gurkirt** [comment]
sorry, not avaible anymore, I lost the access to my previous university's email, models were stored in google-drive that mail, which does not exsit naymore. 
YOu should be able to train again, should take less than 24 hrs on 4 GPUs.

**Comment by Zhang123qian** [comment]
hello
I can't find resnet101.pth document. Where is it?

**Comment by gurkirt** [comment]
what do you mean? there is not trained 101 model.

**Comment by Zhang123qian** [comment]
thanks，Do you have a trained model?

**Comment by gurkirt** [comment]
Unfortunately no, it shouldn't be too hard to train, or move to detection2 or mmdet.
